version: '3'
services:
    zoneminder:
        container_name: zoneminder
        network_mode: bridge
        privileged: true
        ports:
            - '8080:80/tcp'
            - '8443:443/tcp'
            - '9001:9000/tcp'
        environment:
            - TZ=Europe/Athens
            - SHMEM=50%
            - SSL_EVENTS=1
            - PUID=1000
            - PGID=1000
        volumes:
            - '/media/pi/patriot_ssd/zoneminder_cameras:/zoneminder_cams'
            - '/media/pi/patriot_ssd/zoneminder_data:/config:rw'
            - '/media/pi/patriot_ssd/zoneminder_data/cache:/var/cache/zoneminder:rw'
        image: sgarzarella/zoneminder-armhf
