version: '2'
services:


#  jackett:
#    image: linuxserver/jackett
#    container_name: jackett
#    network_mode: host
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Athens
#      - AUTO_UPDATE=true #optional
#      # - RUN_OPTS=<run options here> #optional
#    volumes:
#      - ./volumes/jackett/config:/config
#      - /media/pi/external_a/torrents_downloads:/torrents_downloads
##    ports:
#      - 9117:9117
#    restart: unless-stopped


#   portainer:
#     container_name: portainer
#     image: portainer/portainer-ce
#     restart: unless-stopped
#     network_mode: host
# #    ports:
# #      - 9000:9000
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./volumes/portainer/data:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - /media/pi/external_a/0_media:/media_root
      - /media/pi/external_a/0_media/tv:/tv
      - /media/pi/external_a/0_media/kids:/kids
      - /media/pi/patriot_ssd/torrents_downloads:/torrents_downloads
#    ports:
#      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Athens
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - /media/pi/external_a/0_media/movies:/movies
      - /media/pi/external_a/0_media/classics:/classics
      - /media/pi/external_a/0_media/kids:/kids
      - /media/pi/patriot_ssd/torrents_downloads:/torrents_downloads
#    ports:
#      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/bazarr/config:/config
      - /media/pi/external_a/0_media/tv:/tv
      - /media/pi/external_a/0_media/movies:/movies
      - /media/pi/external_a/0_media/kids:/kids
      - /media/pi/external_a/0_media/classics:/classics
#    ports:
#      - 6767:6767
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - ./volumes/prowlarr/data:/config
#    ports:
#      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: host    
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Athens
    # ports:
    #   - "${PORT:-8191}:8191"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    # image: ghcr.io/linuxserver/plex:bionic
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Athens      
      - UMASK_SET=022 #optional
      # - PLEX_CLAIM= #optional
    volumes:
      - ./volumes/plex/library:/config
      - /media/pi/external_a/0_media/tv:/tv
      - /media/pi/external_a/0_media/movies:/movies
      - /media/pi/external_a/0_media/kids:/kids
      - /media/pi/external_a/0_media/classics:/classics
      - /media/pi/external_a/0_media/books:/books
    restart: unless-stopped


  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - UMASK_SET=022
      - WEBUI_PORT=15080
    volumes:
      - ./volumes/qbittorrent/config:/config
      - /media/pi/patriot_ssd/torrents_downloads:/torrents_downloads
      - ./downloads/torrent_files:/torrent_files      
      - /media/pi/external_a/just_for_seeding:/just_for_seeding      
    # ports:
    #   - 6881:6881
    #   - 6881:6881/udp
    #   - 15080:15080
    #   - 1080:1080
    restart: unless-stopped
  
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    env_file:
      - .env
    container_name: transmission
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - USER=admin
      - PASS=${TRANSMISSION}
    volumes:
      - ./config:/config
      - /media/pi/patriot_ssd/torrents_downloads:/torrents_downloads
      - /media/pi/external_a/just_for_seeding:/just_for_seeding
      - ./downloads/torrent_files:/watch
    # ports:
    #   - 9091:9091
    #   - 51413:51413
    #   - 51413:51413/udp
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /media/pi/external_a/0_media/books:/audiobooks
      # - </path/to/podcasts>:/podcasts
      - ./volumes/audiobookshelf/config:/config
      - ./volumes/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Athens      
    restart: unless-stopped
  
  # openaudible:
  #   image: ghcr.io/lanjelin/openaudible-docker:latest
  #   container_name: openaudible
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Athens
  #     - CUSTOM_USER=nikolas # optional, but recommended if exposing to -
  #     - PASSWORD=XxXxXxXxX1234***!
  #   ports:
  #     - "3000:3000" #http
  #     - "3001:3001" #https
  #   volumes:
  #     - /media/pi/patriot_ssd/OpenAudible:/config/OpenAudible
  #   restart: unless-stopped

   
  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   restart: unless-stopped
  #   network_mode: host
  #   # ports:
  #     # - "8787:8787"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK=002
  #     - TZ=Europe/Athens
  #   volumes:
  #     - ./volumes/readarr/config:/config
  #     - /media/pi/external_a/0_media/books:/books
  #     - /media/pi/patriot_ssd/torrents_downloads:/torrents_downloads
